name: Build and deploy frontend and backend app to Azure

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip apps from /dist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and Nx CLI
        run: |
          npm ci
          npm install -g nx

      - name: Build frontend and backend (with NX daemon disabled)
        env:
          NX_DAEMON: false
          NX_BRANCH: main
        run: |
          npx nx build starstable-wiki --configuration=production
          npx nx build data-api

      - name: Zip artifacts for deployment
        run: |
          cd dist/apps/data-api && zip -r ../../data-api-release.zip ./*
          cd ../starstable-wiki && zip -r ../../starstable-wiki-release.zip ./*

      - name: Upload starstable-wiki artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: starstable-wiki
          path: dist/starstable-wiki-release.zip

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: dist/data-api-release.zip

  deploy-starstable-wiki:
    runs-on: ubuntu-latest
    name: Deploy Angular Frontend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: starstable-wiki

      - name: Unzip artifact for deployment
        run: unzip starstable-wiki-release.zip

      - name: Deploy to static Azure Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_BEACH_0BDF2A703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '.' # Unzipped folder
          api_location: ''
          output_location: ''
          skip_app_build: true

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJS data-api backend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip -d backend

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'starstable-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: ./backend
